library(tidyverse)
library(Seurat)
library(cowplot)
library(patchwork)
library(magrittr)
library(plotly)

setwd("E:/OneDrive - University of Glasgow/2 Projects/2 scRNAseq/S BM B scRNAseq/3 Code")

datadir = "Raw data/"
input.filepath = "Analysis results/1 QC/"
output.filepath = "Analysis results/2 Analysis/"

# Loading File ----
  # Requires Seurat object generated by "QC & normalisation & integration"

  Mm.genes <- readLines(paste0(datadir, "Mm.genes.csv"))
  Mm.combined <- readRDS(paste0(input.filepath, "Mm.combined.rds"))
  head(Mm.combined[[]])
 
  # Subset Spleen ----
  
  S.combined <- subset(Mm.combined, Organ == "S")
  rm(Mm.combined)
  
# Removal of low-UMI cells ----

  VlnPlot(S.combined, "MmUMI", pt.size = 0.1) + scale_y_log10() + geom_hline(yintercept = 1000)
  S.combined <- subset(S.combined, subset = MmUMI >= 1000)
  VlnPlot(S.combined, "MmUMI", pt.size = 0.1) + scale_y_log10()
  dim(S.combined)
  table(S.combined$orig.ident)
  
  # Variable Features, Scaling, PCA ----
  
  DefaultAssay(S.combined) <- "RNA"
  S.combined %<>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 2000) 
  VariableFeaturePlot(S.combined, pt.size = 0.1) 
  
  DefaultAssay(S.combined) <- "integrated"
  S.combined %<>%
    ScaleData(do.scale = TRUE, features = Mm.genes) %<>%
    RunPCA(npcs = 50, verbose = TRUE)
  DimPlot(S.combined, reduction = "pca", group.by = "orig.ident")
  ElbowPlot(S.combined, ndims = 50)
  
  # UMAP and Clustering Parameter optimisation ----
    
  DefaultAssay(S.combined) <- "integrated"
  
  for (i in seq(28, 38, 2)) {

    PCA.dim <- 1:i
    res <- 0.5

    S.combined %<>%
      RunUMAP(reduction = "pca", dims = PCA.dim) %>%
      FindNeighbors(reduction = "pca", dims = PCA.dim)
    S.combined %<>% FindClusters(resolution = res)

    p1 <- DimPlot(S.combined, reduction = "umap", label = T, repel = T) + ggtitle(paste0("PC 1 to ",i)) #+ NoLegend()
    p2 <- DimPlot(S.combined, reduction = "umap", group.by = "predicted.id", label = T)

    print(p1 + p2 )
  }
  
  PCA.dim <- 1:30
  
  S.combined %<>%  
    RunUMAP(reduction = "pca", dims = PCA.dim) %>% 
    FindNeighbors(reduction = "pca", dims = PCA.dim)
  
  for (i in seq(0.3, 0.9, 0.2)) {
    
    res <- i
    
    S.combined %<>% FindClusters(resolution = res)
    
    print(DimPlot(S.combined,reduction = "umap", label = T) + ggtitle(paste0("res ",i)))
    heatmap(table(S.combined$seurat_clusters, S.combined$predicted.id), Rowv = NA, Colv = NA)
    
  }

# UMAP and Clustering ----

  PCA.dim <- 1:30
  res <- 0.5
  
  S.combined %<>%  
    RunUMAP(reduction = "pca", dims = PCA.dim) %>% 
    FindNeighbors(reduction = "pca", dims = PCA.dim)
  S.combined %<>% FindClusters(resolution = res)
  
  p1 <- DimPlot(S.combined, reduction = "umap", label = T, repel = T) #+ NoLegend()
  p2 <- DimPlot(S.combined, reduction = "umap", label = F, group.by = "orig.ident")
  p3 <- DimPlot(S.combined, reduction = "umap", group.by = "predicted.id", label = F)
  p1 + p2 + p3

  VlnPlot(S.combined, "prediction.score.max")
  heatmap(table(S.combined$seurat_clusters, S.combined$predicted.id), Rowv = NA, Colv = NA)

# Marker Genes ----

  DefaultAssay(S.combined) <- "RNA"
  ncluster <- nlevels(Idents(S.combined))
  cluster.list <- vector(mode = "list", length = ncluster)
  names(cluster.list) <- levels(Idents(S.combined))
  
  for (i in 1:nlevels(S.combined)) {
    print(paste0("Working on: #", i, " : ", names(cluster.list)[i], " ..."))
    cluster.list[[i]] <- 
      FindConservedMarkers(S.combined, ident.1 = names(cluster.list)[i], grouping.var = "orig.ident", 
                           assay = "RNA", verbose = TRUE, min.cells.group = 0) %>% 
      rownames_to_column("GeneID")
    cluster.list[[i]][,"ClusterID"] <- names(cluster.list[i]) 
  }
  
  S.combined.marker <- cluster.list
  S.marker <- do.call("rbind", S.combined.marker)
  clipr::write_clip(S.marker) 

  # Annotating Clusters ----
  
  Idents(S.combined) <- S.combined$seurat_clusters
  S.cluster.ids <- c("B cells", "Erythroblasts", "CD4+ T cells", "CD8+ T cells", "Erythroblasts",
                     "Macrophages", "B cells", "NK cells", "Neutrophils", "CD4+ T cells",
                     "Erythroblasts", "Neutrophils", "B cells")

  names(S.cluster.ids) <- levels(S.combined)
  S.combined <- RenameIdents(S.combined, S.cluster.ids)
  DimPlot(S.combined, reduction = "umap", label = T, repel = T)
  
  S.combined$SIdent <- Idents(S.combined)
  
  levels(S.combined) <- c("Erythroblasts", "B cells", "CD4+ T cells", "CD8+ T cells", "NK cells", "Macrophages", "Neutrophils")
  
  S.combined$SIdent <- Idents(S.combined)
  
  col.S <- c("#D6616B", "#393B79", "#7B4173", "#CE6DBD", "#DE9ED6", "#94ab57", "#E7BA52")
  
  DimPlot(S.combined, group.by = "SIdent", cols = col.S)

  # Saving Files ----
  
  saveRDS(S.combined, paste0(output.filepath,"S.combined.rds"))
  saveRDS(S.combined.marker, paste0(output.filepath,"S.conserved.marker.rds"))
  