library(tidyverse)
library(Seurat)
library(cowplot)
library(patchwork)
library(magrittr)
library(plotly)

setwd("E:/OneDrive - University of Glasgow/2 Projects/2 scRNAseq/S BM B scRNAseq/3 Code")

datadir = "Raw data/"
input.filepath = "Analysis results/1 QC/"
output.filepath = "Analysis results/2 Analysis/"

# Loading File ----
# Requires Seurat object generated by "QC & normalisation & integration"
  
  Mm.genes <- readLines(paste0(datadir, "Mm.genes.csv"))
  Mm.combined <- readRDS(paste0(input.filepath, "Mm.combined.rds"))
  head(Mm.combined[[]])

# Subset Bone Marrow ----
  
  BM.combined <- subset(Mm.combined, Organ == "BM")
  rm(Mm.combined)

# Removal of low-UMI cells ----
  
  VlnPlot(BM.combined, "MmUMI", pt.size = 0.1) + scale_y_log10() + geom_hline(yintercept = 1000)
  BM.combined <- subset(BM.combined, subset = MmUMI >= 1000)
  VlnPlot(BM.combined, "MmUMI", pt.size = 0.1) + scale_y_log10()
  dim(BM.combined)
  table(BM.combined$orig.ident)

# Variable Features, Scaling, PCA ----

  DefaultAssay(BM.combined) <- "RNA"
  BM.combined %<>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 2000) 
  VariableFeaturePlot(BM.combined, pt.size = 0.1) 
  
  BM.combined %<>%
    ScaleData(do.scale = TRUE, features = Mm.genes)
  
  DefaultAssay(BM.combined) <- "integrated"
  BM.combined %<>%
    RunPCA(npcs = 50, verbose = TRUE)
  DimPlot(BM.combined, reduction = "pca", group.by = "orig.ident")
  ElbowPlot(BM.combined, ndims = 50)

# UMAP and Clustering Parameter optimisation ----
  
  DefaultAssay(BM.combined) <- "integrated"
  
  for (i in seq(30, 40, 2)) {
    
    PCA.dim <- 1:i
    res <- 0.5
    
    BM.combined %<>%  
      RunUMAP(reduction = "pca", dims = PCA.dim) %>% 
      FindNeighbors(reduction = "pca", dims = PCA.dim)
    BM.combined %<>% FindClusters(resolution = res)
    
    p1 <- DimPlot(BM.combined, reduction = "umap", label = T, repel = T) + ggtitle(paste0(i)) #+ NoLegend()
    p2 <- DimPlot(BM.combined, reduction = "umap", group.by = "predicted.id", label = T)
    
    print(p1 + p2 )
  }
  
  PCA.dim <- 1:38
  
  BM.combined %<>%  
    RunUMAP(reduction = "pca", dims = PCA.dim) %>% 
    FindNeighbors(reduction = "pca", dims = PCA.dim)
  
  for (i in seq(0.5, 1, 0.1)) {
    
    res <- i
    
    BM.combined %<>% FindClusters(resolution = res)
    
    print(DimPlot(BM.combined,reduction = "umap", label = T) + ggtitle(paste0("res ",i)))
    heatmap(table(BM.combined$seurat_clusters, BM.combined$predicted.id), Rowv = NA, Colv = NA)
    
  }

# UMAP and Clustering ----

  PCA.dim <- 1:38
  res <- 0.6
  
  BM.combined %<>%  
    RunUMAP(reduction = "pca", dims = PCA.dim) %>% 
    FindNeighbors(reduction = "pca", dims = PCA.dim)
  BM.combined %<>% FindClusters(resolution = res)
  
  p1 <- DimPlot(BM.combined, reduction = "umap", label = T, repel = T) #+ NoLegend()
  p2 <- DimPlot(BM.combined, reduction = "umap", label = F, group.by = "orig.ident")
  p3 <- DimPlot(BM.combined, reduction = "umap", group.by = "predicted.id", label = F)
  p1 + p2 + p3

  VlnPlot(BM.combined, "prediction.score.max")
  heatmap(table(BM.combined$seurat_clusters, BM.combined$predicted.id), Rowv = NA, Colv = NA)

# Marker Genes ----

  DefaultAssay(BM.combined) <- "RNA"
  Idents(BM.combined) <- BM.combined$seurat_clusters
  ncluster <- nlevels(Idents(BM.combined))
  cluster.list <- vector(mode = "list", length = ncluster)
  names(cluster.list) <- levels(Idents(BM.combined))
  
  for (i in 1:nlevels(BM.combined)) {
    print(paste0("Working on: #", i, " : ", names(cluster.list)[i], " ..."))
    cluster.list[[i]] <- 
      FindConservedMarkers(BM.combined, ident.1 = names(cluster.list)[i], grouping.var = "orig.ident", 
                           assay = "RNA", verbose = TRUE, min.cells.group = 0) %>% 
      rownames_to_column("GeneID")
    cluster.list[[i]][,"ClusterID"] <- names(cluster.list[i]) 
  }
  
  BM.combined.marker <- cluster.list
  BM.marker <- do.call("rbind", BM.combined.marker)
  clipr::write_clip(BM.marker) 
  
  # Renaming Clusters  ----
  
  Idents(BM.combined) <- BM.combined$seurat_clusters
  BM.cluster.ids <- c("Erythroblasts", "Erythroblasts", "Neutrophils", "Neutrophils", "Pre-B cells", 
                      "B cells", "Neutrophils", "Neutrophil Progenitors", "Monocytes", "Pro-Erythroblasts", 
                      "Pre-B cells", "Pro-Erythroblasts", "T cells", "Pro-Erythroblasts", "Pre-B cells", 
                      "HSPCs", "Pro-B cells", "Macrophages", "Pre-B cells", "DCs", 
                      "NK cells", "T cells", "B cells")
  
  names(BM.cluster.ids) <- levels(BM.combined)
  BM.combined <- RenameIdents(BM.combined, BM.cluster.ids)
  DimPlot(BM.combined, reduction = "umap", label = T, repel = F)
  
  levels(BM.combined) <- c("Pro-Erythroblasts", "Erythroblasts", "Pro-B cells", "Pre-B cells", "B cells", 
                           "T cells", "NK cells", "Monocytes", "Macrophages", "Neutrophil Progenitors",
                           "Neutrophils", "DCs", "HSPCs")
  
  BM.combined$BMIdent <- Idents(BM.combined)
  
  col.BM <- c("#82393f", "#D6616B", "#9C9EDE", "#6B6ECF", "#393B79",
              "#A55194", "#DE9ED6","#59753e", "#94ab57", "#b38839",
              "#E7BA52", "#9c446d", "#705828")
  
  DimPlot(BM.combined, group.by = "BMIdent", cols = col.BM)
  clipr::write_clip(table(BM.combined$orig.ident, BM.combined$BMIdent))

  # Saving Files ----
  
  saveRDS(BM.combined, paste0(output.filepath,"BM.combined.rds"))
  saveRDS(BM.combined.marker, paste0(output.filepath,"BM.conserved.marker.rds"))
